apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "core-pipeline.fullname" . }}-config
  labels:
    {{- include "core-pipeline.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  METRICS_ENABLED: {{ .Values.env.METRICS_ENABLED | quote }}
  TRACING_ENABLED: {{ .Values.env.TRACING_ENABLED | quote }}