apiVersion: v2
name: core-pipeline
description: A Helm chart for Core Pipeline application
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - nestjs
  - api
  - observability

maintainers:
  - name: DevOps Team
    email: devops@example.com

dependencies: []