replicaCount: 3

image:
  tag: "main"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "100"
  hosts:
    - host: core-pipeline.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: core-pipeline-tls
      hosts:
        - core-pipeline.example.com

env:
  - name: NODE_ENV
    value: "production"
  - name: LOG_LEVEL
    value: "info"

configMap:
  kafka:
    brokers: "prod-kafka-1:9092,prod-kafka-2:9092,prod-kafka-3:9092"
  postgres:
    host: "prod-postgres.rds.amazonaws.com"
    database: "core_pipeline_prod"
  redis:
    host: "prod-redis.cache.amazonaws.com"

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 75