replicaCount: 3

image:
  tag: "main"

ingress:
  enabled: true
  hosts:
    - host: core-pipeline.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: core-pipeline-tls
      hosts:
        - core-pipeline.example.com

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20

env:
  NODE_ENV: production
  LOG_LEVEL: warn

kafka:
  brokers: "kafka-0.kafka-prod.svc.cluster.local:9092,kafka-1.kafka-prod.svc.cluster.local:9092,kafka-2.kafka-prod.svc.cluster.local:9092"

postgres:
  host: postgres-prod.database.svc.cluster.local
  database: core-pipeline-prod

redis:
  host: redis-prod.cache.svc.cluster.local