name: Deploy PR to Testing

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request number to deploy'
        required: true
        type: number

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy-pr:
    name: Deploy PR to Testing
    runs-on: ubuntu-latest
    environment:
      name: testing
      url: https://pr-${{ github.event.inputs.pr_number }}.test.theedgestory.org
    permissions:
      contents: read
      packages: write
      pull-requests: write
    
    steps:
      - name: Get PR details
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.inputs.pr_number }}
            });
            core.setOutput('branch', pr.data.head.ref);
            core.setOutput('sha', pr.data.head.sha);
            core.setOutput('short_sha', pr.data.head.sha.substring(0, 7));
            return pr.data;
      
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr.outputs.sha }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=pr-${{ github.event.inputs.pr_number }}
            type=raw,value=pr-${{ github.event.inputs.pr_number }}-${{ steps.pr.outputs.short_sha }}
      
      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=${{ steps.meta.outputs.created }}
            VCS_REF=${{ steps.pr.outputs.sha }}
            VERSION=pr-${{ github.event.inputs.pr_number }}
      
      - name: Checkout core-charts repository
        uses: actions/checkout@v4
        with:
          repository: uz0/core-charts
          token: ${{ secrets.CORE_CHARTS_PAT }}
          path: core-charts
      
      - name: Update Helm values for testing
        run: |
          cd core-charts
          IMAGE_TAG="pr-${{ github.event.inputs.pr_number }}-${{ steps.pr.outputs.short_sha }}"
          
          # Update the image tag in test values
          yq eval ".image.tag = \"${IMAGE_TAG}\"" -i charts/core-pipeline/values-test.yaml
          
          # Update PR-specific annotations
          yq eval ".ingress.hosts[0].host = \"pr-${{ github.event.inputs.pr_number }}.test.theedgestory.org\"" -i charts/core-pipeline/values-test.yaml
          
          # Show the changes
          echo "Updated values-test.yaml for PR #${{ github.event.inputs.pr_number }}"
          git diff
      
      - name: Commit and push changes
        run: |
          cd core-charts
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add charts/core-pipeline/values-test.yaml
          git commit -m "Deploy PR #${{ github.event.inputs.pr_number }} to testing" || echo "No changes to commit"
          git push
      
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `### 🚀 Deployed to Testing Environment
            
            PR #${{ github.event.inputs.pr_number }} has been deployed successfully!
            
            - **URL:** https://pr-${{ github.event.inputs.pr_number }}.test.theedgestory.org
            - **Image:** \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pr-${{ github.event.inputs.pr_number }}-${{ steps.pr.outputs.short_sha }}\`
            - **Commit:** \`${{ steps.pr.outputs.sha }}\`
            
            The deployment will remain active until replaced by another PR deployment.`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.inputs.pr_number }},
              body: comment
            });